name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Change this to master if your default branch is master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Web Artifact
        run: |
          cd SUERTE_ACTIVITY_6
          flutter build web --release --base-href "lestersuerte.github.io/"

      - name: Deploy to GitHub Pages Repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: geniusqwerty12/geniusqwerty12.github.io
          publish_dir: ./SUERTE_ACTIVITY_6/build/web
          publish_branch: main
          
